name: Check Marvel characters
on:
  workflow_dispatch:
    inputs:
      First_Movie:
        default: "Iron Man"
      Second_Movie:
        default: "The Incredible Hulk"
env: 
  MONGODB_DB_NAME: "DB name"
jobs:
  test:
    env:
      MONGODB_CLUSTER_ADDRESS: "address"
    environment: testing
    runs-on: ubuntu-latest
    steps:
       - run: |
          echo "List of marvel movies"
          echo "${{ github.event.inputs.First_Movie }}"
          echo "${{ github.event.inputs.Second_Movie }}"    
          echo "${{ env.MONGODB_CLUSTER_ADDRESS }}"
          echo "${{ env.MONGODB_DB_NAME }}"
          echo "${{ vars.VARIABLEEXAMPLE }}"
          echo "${{ secrets.MONGODB_DB_NAME }}"
